---

- name: Copy executing file
  ansible.builtin.copy:
    src: var/temp/bin/temp.sh
    dest: /var/temp/bin/temp.sh
    owner: user
    group: user
    mode: 0754

- name: Copy config file
  ansible.builtin.copy:
    src: var/temp/conf/temp.conf
    dest: /var/temp/conf/temp.conf
    owner: user
    group: user
    mode: u=rw,g=r,o=r

